"""Add created_at to Comment

Revision ID: 452f647ca947
Revises: 0c0cc2a6de4d
Create Date: 2025-07-19 14:09:44.811966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '452f647ca947'
down_revision = '0c0cc2a6de4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               nullable=False)
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
